### PR TITLE
Make homepage, FAQ and speakers index pages responsive

### PR DESCRIPTION
**Pull request by weepotty**
This PR makes the homepage, FAQ and speakers index pages responsive.
I've hidden the purple ellipse on mobile for now - i can't work out how to make it responsive and not look weird - what do you think?
I've adjusted the number of slides per view in the carousel so that it goes from 4-3-2-1 as the screen size gets progressively smaller.. see what you think!

### CODE REVIEW

**Comment by ayushn21** [comment]
Great work ... I don't have any feedback regarding your code, but there's a few design issues we should address:

Screenshot 2023-06-20 at 11 24 54 am

This one card is bigger than the rest ... every card should ideally be the same size .... not sure what to do about the long text ... I guess we could just hope that all the real values fit and if there's an issue we'll figure out how to fix it then.

Screenshot 2023-06-20 at 11 26 01 am

I think we should get rid of the vertical borders either side of the page at 1200px. They compress the content too much otherwise. Also, let's hide the ticket button in the nav bar once it wraps to a second line, it just looks weird in that kind of layout. It's there in the hero section anyway so it's not a problem.

I think we should also make the logo a bit smaller. Have a play around with it and see what you like!

**Comment by ayushn21** [comment]
> I've hidden the purple ellipse on mobile for now - i can't work out how to make it responsive and not look weird - what do you think?

Yeah that's fair, I don't like it in the first place but I'll have a fiddle with it when I do my refactor and see what's what.

> I've adjusted the number of slides per view in the carousel so that it goes from 4-3-2-1 as the screen size gets progressively smaller.. see what you think!

Looks good, but can we step down in fractions at all? 4.5, 3.5 and so on?

**Comment by weepotty** [comment]
yeah i agree that taller card looks out of place.. but wasnt sure what to do with longer text. in the speakers index page i tihnk we can fix this problem by using ellipsis (...). what do you think? 

Screenshot 2023-06-20 at 8 29 19 PM

unfortunately when i try this in the carousel it completely mucks it up because of the `white-space: nowrap`.. so the solution would maybe be setting fixed height and width (which i don't love, but not sure how else we standardise the height with varying content length)


> Great work ... I don't have any feedback regarding your code, but there's a few design issues we should address:
> 
> Screenshot 2023-06-20 at 11 24 54 am
> This one card is bigger than the rest ... every card should ideally be the same size .... not sure what to do about the long text ... I guess we could just hope that all the real values fit and if there's an issue we'll figure out how to fix it then.
> 
> Screenshot 2023-06-20 at 11 26 01 am
> I think we should get rid of the vertical borders either side of the page at 1200px. They compress the content too much otherwise. Also, let's hide the ticket button in the nav bar once it wraps to a second line, it just looks weird in that kind of layout. It's there in the hero section anyway so it's not a problem.
> 
> I think we should also make the logo a bit smaller. Have a play around with it and see what you like!

**Comment by ayushn21** [comment]
I like the ellipsis 👍 ... let's avoid setting a fixed height and width for now and just hope there's no company name long enough to wrap to the next line 🙈 ... if there is we'll deal with it then .... might have to set a fixed height and width in that case.

**Comment by weepotty** [comment]
can't decide.. what do you reckon? 50% or 60% logo size?

Screenshot 2023-06-20 at 8 48 45 PM
Screenshot 2023-06-20 at 8 48 37 PM

**Comment by ayushn21** [comment]
> can't decide.. what do you reckon? 50% or 60% logo size?

The 60% size looks good, but let's not define it in %. On very narrow screens (iPhone 13 mini and the like), 60% will be too small. Let's use the `max-width` property to limit it to a pixel width, and then maybe use `margin-left` and `margin-right` to ensure there's a minimum clearance from the viewport edges.

I don't actually know off the top of my head the combination of properties which will do what I've got in my head. What I'm thinking is that we set an upper limit size which is about the largest the logo can be ... and then if that's too big as the screen size gets smaller, then the logo keeps scaling down with the screen. Does that make sense? 

Let me know if you run into any issues.

**Comment by weepotty** [comment]
> > can't decide.. what do you reckon? 50% or 60% logo size?
> 
> The 60% size looks good, but let's not define it in %. On very narrow screens (iPhone 13 mini and the like), 60% will be too small. Let's use the `max-width` property to limit it to a pixel width, and then maybe use `margin-left` and `margin-right` to ensure there's a minimum clearance from the viewport edges.
> 
> I don't actually know off the top of my head the combination of properties which will do what I've got in my head. What I'm thinking is that we set an upper limit size which is about the largest the logo can be ... and then if that's too big as the screen size gets smaller, then the logo keeps scaling down with the screen. Does that make sense?
> 
> Let me know if you run into any issues.

i've actually used `25em`, is that ok? the `.nav` itself has a padding so it won't stick to the viewport edges

**Comment by ayushn21** [comment]
> I've actually used 25em, is that ok? the .nav itself has a padding so it won't stick to the viewport edges

Yup that's fine!

**Comment by ayushn21** [comment]
> not sure if you saw my comment re. scroll-hint above for the carousel, but you can see how that looks now

Ah no I missed that. I'll take a peek in a bit!

I think this is mostly good to go though so could you please clean up the commits? I'll pull the branch and take a peek in a bit and then merge it ... might be a bit late for you by the time I get to it.

**Pull request merged**
